### ISSUE TITLE
Add extra branch to mirror cimgui's "docking_inter" branch

### ISSUE THREAD

**Issue by kathrindc** [fips-libs/fips-cimgui#1]
Hi there,
I was wondering if it would be realistic to add support for ImGui's docking features to this repo. The upstream cimgui repository has a separate branch which uses ImGui's `docking` branch as a base. Would it be feasible to mirror this over here as well?

**Comment by floooh** [comment]
Yeah I think it's possible, just not with a branch but a separate git repo, e.g. this the docking version of the regular fips-imgui: https://github.com/fips-libs/fips-imgui-dock, which simply pins the imgui submodule to a docking tag.

IIRC when I created the fips-cimgui repository, the cimgui repo didn't have docking tags, but looks like it does now.

I can take care of that in the next days, will also create a new docking sample similar to https://floooh.github.io/sokol-html5/imgui-dock-sapp.html.

**Comment by floooh** [comment]
Btw this is now solved differently: I created an entirely new all-in-one dcimgui repo which contains both the regular and docking Dear ImGui version as well as new C bindings which are generated with the new dear_bindings approach (https://github.com/dearimgui/dear_bindings) - there *are* some differences in the C API, but IMHO for the better :)

PS: new repo is here: https://github.com/floooh/dcimgui
